name = "rpg-timeline-public-editor"
main = "src/index.js"
compatibility_date = "2026-08-26"

[vars]
OWNER = "CleoMelo"
REPO = "rpg"
BRANCH = "import-timeline-cavaleiros"
TIMELINE_PATH = "timeline/timeline.json"

workers_dev = true
